// 24 estados de Venezuela + Distrito Capital
export const VENEZUELA_ESTADOS = [
  "AMAZONAS",
  "ANZOÁTEGUI",
  "APURE",
  "ARAGUA",
  "BARINAS",
  "BOLÍVAR",
  "CARABOBO",
  "COJEDES",
  "DELTA AMACURO",
  "DISTRITO CAPITAL",
  "FALCÓN",
  "GUÁRICO",
  "GUAYANA",
  "LA GUAIRA",
  "LARA",
  "MÉRIDA",
  "MIRANDA",
  "MONAGAS",
  "NUEVA ESPARTA",
  "PORTUGUESA",
  "SUCRE",
  "TÁCHIRA",
  "TRUJILLO",
  "YARACUY",
  "ZULIA",
] as const;

export type VenezuelaEstado = (typeof VENEZUELA_ESTADOS)[number];
